# Generated by Django 5.2.8 on 2025-11-11 12:07

import task5.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task5', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=task5.models.upload_to)),
                ('original_name', models.CharField(max_length=200)),
                ('extension', models.CharField(max_length=10)),
                ('mime_type', models.CharField(max_length=100)),
                ('size_bytes', models.BigIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('is_image', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
