# Generated by Django 5.2.8 on 2025-11-11 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task5', '0002_upload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
        migrations.AlterField(
            model_name='upload',
            name='size_bytes',
            field=models.IntegerField(),
        ),
    ]
